<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('user_payments', function (Blueprint $table) {
            // development_partner = 37.5% resource share, business_developer = 5-6% commission share
            $table->string('share_type')->nullable()->after('developer_id');
            // project = earned by a development partner, salary_employee = earned by salary staff (only BD commission applies)
            $table->string('earning_type')->default('project')->after('share_type');
        });

        // Backfill existing rows: entries generated by the system or owned by the
        // business developers (Ayub = 3, Ali Hasan = 147) are commission shares.
        DB::table('user_payments')
            ->where('generated_by_system', true)
            ->orWhereIn('developer_id', [3, 147])
            ->update(['share_type' => 'business_developer']);

        DB::table('user_payments')
            ->whereNull('share_type')
            ->update(['share_type' => 'development_partner']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('user_payments', function (Blueprint $table) {
            $table->dropColumn(['share_type', 'earning_type']);
        });
    }
};
