<?php
// config/motivationalQuotes.php

return [
    'The only way to do great work is to love what you do. - Steve Jobs',
    'Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer',
    'Believe you can and you\'re halfway there. - Theodore Roosevelt',
    'Don\'t watch the clock; do what it does. Keep going. - Sam Levenson',
    'Dream big and dare to fail. - Norman Vaughan',
    'The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt',
    'You are never too old to set another goal or to dream a new dream. - C.S. Lewis',
    'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs',
    'The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt',
    'Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill',
    'The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb',
    'If you can dream it, you can achieve it. - Zig Ziglar',
    'The only person you should try to be better than is the person you were yesterday. - Matty Mullins',
    'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett',
    'Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill',
    'The harder you work for something, the greater you\'ll feel when you achieve it. - Unknown',
    'The secret to success is to know something nobody else knows. - Aristotle Onassis',
    'The road to success and the road to failure are almost exactly the same. - Colin R. Davis',
    'Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau',
    'Your positive action combined with positive thinking results in success. - Shiv Khera',
    'Success is not just about making money. It\'s about making a difference. - Unknown',
    'The only place where success comes before work is in the dictionary. - Vidal Sassoon',
    'You are the only one who can limit your greatness. - Unknown',
    'Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou',
    'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi',
    'Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson',
    'There is no substitute for hard work. - Thomas Edison',
    'Opportunities don\'t happen. You create them. - Chris Grosser',
    'The starting point of all achievement is desire. - Napoleon Hill',
    'The only person you should try to be better than is the person you were yesterday. - Unknown',
    'The successful warrior is the average man, with laser-like focus. - Bruce Lee',
    'You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win. - Zig Ziglar'
];
